development:
  adapter: postgresql
  encoding: unicode
  database: exclusive
  pool: 5
  username: exclusive
  password: exete4_ws_sdkic

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: exclusivetver_development
  pool: 5
  username: exclusivetver
  password: 478w23rdefbvt53w