development:
  adapter: postgresql
  encoding: unicode
  database: exclusive
  pool: 5
  username: exclusive
  password: exete4_ws_sdkic

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: abbb_exclusive25
  pool: 5
  username: abbb_exclusive25
  password: a8czHucH
  host: mysql0.locum.ru